AppName = "OnlinePan"
PrintConfig = false
RunMode = "debug"

[CORS]
  AllowCredentials = true
  AllowHeaders = []
  AllowMethods = ["GET", "POST", "PUT", "DELETE", "PATCH"]
  AllowOrigins = ["*"]
  Enable = false
  MaxAge = 7200

[Captcha]
  Height = 30
  Length = 1
  Width = 150

[Download]
  Limit = 100

[Email]
  Host = "smtp.163.com"
  Password = "BGCFWYIIDGATRQLO"
  Port = "25"
  UserName = "lj_5683@163.com"

[File]
  FileUploadDir = "upload"
  InitSpaceSize = 102400

[GZIP]
  Enable = true
  ExcludedExtentions = [".png", ".gif", ".jpeg", ".jpg"]
  ExcludedPaths = []

[Gorm]
  DBType = "mysql"
  Debug = false
  EnableAutoMigrate = true
  MaxIdleConns = 50
  MaxLifetime = 43200
  MaxOpenConns = 150
  TablePrefix = "tb_"

[HTTP]
  CertFile = ""
  Host = "0.0.0.0"
  KeyFile = ""
  MaxContentLength = 67108864
  MaxReqLoggerLength = 1024
  MaxResLoggerLength = 1024
  Port = 8081
  ShutdownTimeout = 30

[JWTAuth]
  Enable = true
  Expired = 86400
  FilePath = "data/jwt_auth.db"
  RedisDB = 10
  RedisPrefix = "auth_"
  SigningKey = "NetCloud"
  SigningMethod = "HS512"
  Store = "redis"

[MySQL]
  DBName = "NetCloud"
  Host = "localhost"
  Parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"
  Password = "U2FsdGVkX1sc"
  Port = 23560
  User = "root"

[RateLimiter]
  Count = 100
  Enable = false
  RedisDB = 10

[Redis]
  Addr = "ljcctv.bf:23561"
  Password = "U2FsdGVkX1sc"
